<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SurveyData;

class SurveyDatasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SurveyData::create([
            'id' => 1,
            'lastName' => 'ADlkjflskd',
            'firstName' => 'dlafjs',
            'age' => 25,
            'sex' => 'asfa',
            'occupation' => 'dkajkfklds',
            'citizenship' => 'dlskagg',
            'phoneNumber' => '12345678',
            'reserveNumber' => '12345678',
            'email' => 'jsadfla@dslka.com',
            'facebookAddress' => 'sdalkfdg',
            'interest' => 'ldkjasldkjfa',
            'activity' => 'sdalkjfalskjdga',
            'selfExpectation' => 'lkjaflskdjgalksdg',
            'volunteering' => 'lksdlskdgjaldsg',
            'advantage' => 'dakjsdgasdgadsh',
            'disadvantage' => 'dslkajasldkgja',
            'purpose' => 'dklasjdgsalsg',
        ]);

        SurveyData::create([
            'id' => 2,
            'lastName' => 'ADlkjfdsgalskd',
            'firstName' => 'gkae',
            'age' => 21,
            'sex' => 'male',
            'occupation' => 'dsalkjadsajkfklds',
            'citizenship' => 'dlsdksga',
            'phoneNumber' => '12345568',
            'reserveNumber' => '12356678',
            'email' => 'jsadfla@ddsk.com',
            'facebookAddress' => 'sgkljgkfdg',
            'interest' => 'ldkjasfkjaeg',
            'activity' => 'sdalkjffekljag',
            'selfExpectation' => 'lklkgjskdjgalksdg',
            'volunteering' => 'lksdlfewakjaldsg',
            'advantage' => 'dakjsfekajgdsh',
            'disadvantage' => 'dsfvsdkljsldkgja',
            'purpose' => 'dklasjddlksj',
        ]);

        SurveyData::create([
            'id' => 3,
            'lastName' => 'Өлзийсүрэн',
            'firstName' => 'Базарсад',
            'age' => 21,
            'sex' => 'male',
            'occupation' => 'Оюутан',
            'citizenship' => 'Улаанбаатар',
            'phoneNumber' => '99112233',
            'reserveNumber' => '12356678',
            'email' => 'bazraabazraa648@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/bazarsad.ulziisuren',
            'interest' => 'Хүнд туслах',
            'activity' => 'Хүнд туслах',
            'selfExpectation' => 'Хүнд туслах',
            'volunteering' => 'Хүнд туслах',
            'advantage' => 'Хүнд туслах',
            'disadvantage' => 'Хүнд туслах',
            'purpose' => 'Хүнд туслах',
        ]);

        SurveyData::create([
            'id' => 4,
            'lastName' => 'Мэндбаяр',
            'firstName' => 'Баасанбаяр',
            'age' => 22,
            'sex' => 'male',
            'occupation' => 'Оюутан',
            'citizenship' => 'Дархан',
            'phoneNumber' => '99112233',
            'reserveNumber' => '12356678',
            'email' => 'athenda.mng@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/profile.php?id=100009969307872',
            'interest' => 'Веб хөгжүүлэх',
            'activity' => 'Веб хөгжүүлэх',
            'selfExpectation' => 'Веб хөгжүүлэх',
            'volunteering' => 'Веб хөгжүүлэх',
            'advantage' => 'Веб хөгжүүлэх',
            'disadvantage' => 'Веб хөгжүүлэх',
            'purpose' => 'Веб хөгжүүлэх',
        ]);
        SurveyData::create([
            'id' => 5,
            'lastName' => 'Мижиддорж',
            'firstName' => 'Уянга',
            'age' => 21,
            'sex' => 'female',
            'occupation' => 'Оюутан',
            'citizenship' => 'Дархан',
            'phoneNumber' => '99112233',
            'reserveNumber' => '12356678',
            'email' => 'mijiddorjuyanga@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/demonikaZ/',
            'interest' => 'идэх',
            'activity' => 'идэх',
            'selfExpectation' => 'идэх',
            'volunteering' => 'идэх',
            'advantage' => 'идэх',
            'disadvantage' => 'идэх',
            'purpose' => 'идэх',
        ]);
        SurveyData::create([
            'id' => 6,
            'lastName' => 'Алтанзул',
            'firstName' => 'Дэлгэрсайхан',
            'age' => 20,
            'sex' => 'male',
            'occupation' => 'Оюутан',
            'citizenship' => 'Улаанбаатар',
            'phoneNumber' => '99332233',
            'reserveNumber' => '12356678',
            'email' => 'deegiideegii00@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/profile.php?id=100005765805891',
            'interest' => 'Веб хөгжүүлэх',
            'activity' => 'Веб хөгжүүлэх',
            'selfExpectation' => 'Веб хөгжүүлэх',
            'volunteering' => 'Веб хөгжүүлэх',
            'advantage' => 'Веб хөгжүүлэх',
            'disadvantage' => 'Веб хөгжүүлэх',
            'purpose' => 'Веб хөгжүүлэх',
        ]);
        SurveyData::create([
            'id' => 7,
            'lastName' => 'Батчулуун',
            'firstName' => 'Амаржаргал',
            'age' => 20,
            'sex' => 'male',
            'occupation' => 'Оюутан',
            'citizenship' => 'Эрдэнэт',
            'phoneNumber' => '99123456',
            'reserveNumber' => '12356678',
            'email' => 'amarjargalamraa61@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/amarjargal.batchuluun.16/',
            'interest' => 'Веб хөгжүүлэх',
            'activity' => 'Веб хөгжүүлэх',
            'selfExpectation' => 'Веб хөгжүүлэх',
            'volunteering' => 'Веб хөгжүүлэх',
            'advantage' => 'Веб хөгжүүлэх',
            'disadvantage' => 'Веб хөгжүүлэх',
            'purpose' => 'Веб хөгжүүлэх',
        ]);
        SurveyData::create([
            'id' => 8,
            'lastName' => 'Овог',
            'firstName' => 'Нэр',
            'age' => 23,
            'sex' => 'female',
            'occupation' => 'Оюутан',
            'citizenship' => 'Дархан',
            'phoneNumber' => '99889999',
            'reserveNumber' => '12356678',
            'email' => 'uiangam@yahoo.com',
            'facebookAddress' => 'https://www.facebook.com/profile.php?id=100009969307872',
            'interest' => 'идэх',
            'activity' => 'уух',
            'selfExpectation' => 'Веб хөгжүүлэх',
            'volunteering' => 'байхгүй',
            'advantage' => 'Бүгдийг иднэ',
            'disadvantage' => 'Хаана ч унтана',
            'purpose' => 'Турах',
        ]);
        SurveyData::create([
            'id' => 9,
            'lastName' => 'Randomовог',
            'firstName' => 'Нэрrandom',
            'age' => 30,
            'sex' => 'male',
            'occupation' => 'Зураач',
            'citizenship' => 'Дархан',
            'phoneNumber' => '99732459',
            'reserveNumber' => '12356678',
            'email' => 'uyanga.mijiddorjj@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/profile.php?id=100009969307872',
            'interest' => 'Гэрэл зураг авах',
            'activity' => 'ууланд алхах',
            'selfExpectation' => 'Веб хөгжүүлэх',
            'volunteering' => 'Веб хөгжүүлэх',
            'advantage' => 'Бүгдийг зурна',
            'disadvantage' => 'Унтамхай',
            'purpose' => 'Хүн байх',
        ]);
        SurveyData::create([
            'id' => 10,
            'lastName' => Str::random(10),
            'firstName' => Str::random(10),
            'age' => 19,
            'sex' => 'female',
            'occupation' => 'сурагч',
            'citizenship' => 'Сэлэнгэ',
            'phoneNumber' => '99002233',
            'reserveNumber' => '12356678',
            'email' => 'demonikazzzz@gmail.com',
            'facebookAddress' => 'https://www.facebook.com/profile.php?id=100009969307872',
            'interest' => 'галаар тоглох',
            'activity' => 'Веб хөгжүүлэх',
            'selfExpectation' => 'Веб хөгжүүлэх',
            'volunteering' => 'Веб хөгжүүлэх',
            'advantage' => 'шатахгүй',
            'disadvantage' => 'амьд байх магадлал багатай',
            'purpose' => 'Бүгдийг шатаах',
        ]);
        SurveyData::create([
            'id' => 11,
            'lastName' => Str::random(10),
            'firstName' => Str::random(10),
            'age' => 18,
            'sex' => 'male',
            'occupation' => 'сурагч',
            'citizenship' => Str::random(10),
            'phoneNumber' => '99080808',
            'reserveNumber' => '12356678',
            'email' => 'uiangam@yahoo.com',
            'facebookAddress' => 'https://www.facebook.com/profile.php?id=100009969307872',
            'interest' => 'сэлэх',
            'activity' => 'сэлэх',
            'selfExpectation' => 'сэлэх',
            'volunteering' => 'сэлэх',
            'advantage' => 'хаана ч сэлнэ',
            'disadvantage' => 'живэх магадлал өндөр',
            'purpose' => 'Олимпийн аварга бэлтгэх',
        ]);

    }
}
